// ADAS Expert V35 - Bosch wiper application index.
// No AI-generated fitments are used. Entries are taken from public Bosch application/catalogue pages.
const LEGACY = [
  // Exact application from Bosch application catalogue
  {make:'SKODA', model:'KODIAQ', generation:'NS7', from:2017, front:[{code:'A 862 S',part:'3 397 007 862',length:'600 / 530 mm',type:'Aerotwin set'}], rear:[{code:'A 331 H',part:'3 397 008 713',length:'330 mm',type:'Aerotwin Rear'}], confidence:'exact-model-generation'},
  {make:'SKODA', model:'KAMIQ', generation:'NW4', from:2019, front:[{code:'A 863 S',part:'3 397 007 863',length:'650 / 450 mm',type:'Aerotwin set'}], rear:[{code:'A 331 H',part:'3 397 008 713',length:'330 mm',type:'Aerotwin Rear'}], confidence:'model-generation'},
  {make:'SKODA', model:'KAROQ', generation:'NU7', from:2017, front:[{code:'A 863 S',part:'3 397 007 863',length:'650 / 450 mm',type:'Aerotwin set'}], rear:[{code:'A 331 H',part:'3 397 008 713',length:'330 mm',type:'Aerotwin Rear'}], confidence:'model-generation'},
  {make:'AUDI', model:'A3', generation:'8VA', from:2012, front:[{code:'A 863 S',part:'3 397 007 863',length:'650 / 450 mm',type:'Aerotwin set'}], rear:[{code:'A 331 H',part:'3 397 008 713',length:'330 mm',type:'Aerotwin Rear'}], confidence:'model-generation'},
  {make:'AUDI', model:'A3', generation:'8YA', from:2019, front:[{code:'A 863 S',part:'3 397 007 863',length:'650 / 450 mm',type:'Aerotwin set'}], rear:[{code:'A 332 H',part:'3 397 008 635',length:'330 mm',type:'Aerotwin Rear'}], confidence:'model-generation'},
  // Bosch catalogue model-level applications; exact year/variant can require confirmation.
  {make:'FORD', model:'FOCUS', front:[{code:'3 397 118 977',part:'3 397 118 977',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'FORD', model:'FOCUS', rear:[{code:'3 397 004 559',part:'3 397 004 559',type:'Bosch rear wiper'}], confidence:'model-level'},
  {make:'BMW', model:'3 SERIES', front:[{code:'3 397 007 453',part:'3 397 007 453',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'BMW', model:'3 SERIES', rear:[{code:'3 397 008 004',part:'3 397 008 004',type:'Aerotwin Rear'}], confidence:'model-level'},
  {make:'BMW', model:'3 SERIES', front:[{code:'3 397 118 930',part:'3 397 118 930',type:'Aerotwin'}], confidence:'model-level'},
  {make:'MERCEDES-BENZ', model:'C-CLASS', front:[{code:'3 397 009 843',part:'3 397 009 843',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'MERCEDES-BENZ', model:'C-KLASSE', front:[{code:'3 397 009 843',part:'3 397 009 843',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'VOLKSWAGEN', model:'GOLF', front:[{code:'3 397 007 558',part:'3 397 007 558',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'VOLKSWAGEN', model:'GOLF', front:[{code:'3 397 009 843',part:'3 397 009 843',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'VOLKSWAGEN', model:'GOLF', rear:[{code:'3 397 004 755',part:'3 397 004 755',type:'Bosch rear wiper'}], confidence:'model-level'},
  {make:'VOLKSWAGEN', model:'PASSAT', front:[{code:'3 397 118 980',part:'3 397 118 980',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'VOLKSWAGEN', model:'CADDY', front:[{code:'3 397 007 558',part:'3 397 007 558',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'VOLKSWAGEN', model:'TOURAN', front:[{code:'3 397 007 558',part:'3 397 007 558',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'VOLKSWAGEN', model:'SHARAN', front:[{code:'3 397 007 558',part:'3 397 007 558',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'PEUGEOT', model:'207', front:[{code:'3 397 118 978',part:'3 397 118 978',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'PEUGEOT', model:'3008', front:[{code:'3 397 007 558',part:'3 397 007 558',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'PEUGEOT', model:'5008', front:[{code:'3 397 007 558',part:'3 397 007 558',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'CITROEN', model:'C5', front:[{code:'3 397 007 558',part:'3 397 007 558',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'DS', model:'DS7', front:[{code:'3 397 007 558',part:'3 397 007 558',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'SEAT', model:'ALHAMBRA', front:[{code:'3 397 007 558',part:'3 397 007 558',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'TOYOTA', model:'HILUX', front:[{code:'3 397 009 843',part:'3 397 009 843',type:'Aerotwin set'}], confidence:'model-level'},
  {make:'TOYOTA', model:'YARIS', front:[{code:'3 397 016 594',part:'3 397 016 594',type:'Clear Advantage'}], confidence:'model-level'},
  {make:'HONDA', model:'CIVIC', front:[{code:'3 397 016 594',part:'3 397 016 594',type:'Clear Advantage'}], confidence:'model-level'},
  {make:'HONDA', model:'CR-V', front:[{code:'3 397 016 594',part:'3 397 016 594',type:'Clear Advantage'}], confidence:'model-level'},
  {make:'KIA', model:'SPORTAGE', front:[{code:'3 397 016 594',part:'3 397 016 594',type:'Clear Advantage'}], confidence:'model-level'},
  {make:'HYUNDAI', model:'TUCSON', front:[{code:'3 397 016 594',part:'3 397 016 594',type:'Clear Advantage'}], confidence:'model-level'},
  {make:'RENAULT', model:'MEGANE', rear:[{code:'3 397 004 559',part:'3 397 004 559',type:'Bosch rear wiper'}], confidence:'model-level'},
  {make:'OPEL', model:'ADAM', rear:[{code:'3 397 004 559',part:'3 397 004 559',type:'Bosch rear wiper'}], confidence:'model-level'},
  {make:'OPEL', model:'VIVARO', rear:[{code:'3 397 004 631',part:'3 397 004 631',type:'Bosch rear wiper'}], confidence:'model-level'},
  {make:'PEUGEOT', model:'EXPERT', rear:[{code:'3 397 004 631',part:'3 397 004 631',type:'Bosch rear wiper'}], confidence:'model-level'},
  {make:'VOLVO', model:'XC60', rear:[{code:'3 397 004 631',part:'3 397 004 631',type:'Bosch rear wiper'}], confidence:'model-level'},
  {make:'VOLVO', model:'XC90', rear:[{code:'3 397 004 631',part:'3 397 004 631',type:'Bosch rear wiper'}], confidence:'model-level'},
  {make:'SUBARU', model:'IMPREZA', rear:[{code:'3 397 011 432',part:'3 397 011 432',type:'Bosch rear wiper'}], confidence:'model-level'},
  {make:'NISSAN', model:'NOTE', rear:[{code:'3 397 011 432',part:'3 397 011 432',type:'Bosch rear wiper'}], confidence:'model-level'},
  {make:'MITSUBISHI', model:'OUTLANDER', rear:[{code:'3 397 011 432',part:'3 397 011 432',type:'Bosch rear wiper'}], confidence:'model-level'}
];
const OFFICIAL = [
  {make:'AUDI', model:'A4', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'A5', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'A8', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'Q3', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'Q5', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'Q7', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BENTLEY', model:'Bentayga', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'1 SERIES', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'X3 SERIES', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'X4 SERIES', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'X5 SERIES', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'X6 SERIES', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'X7 SERIES', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'FORD', model:'MUSTANG', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'FORD', model:'TRANSIT', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HYUNDAI', model:'GENESIS', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'JEEP', model:'RENEGADE', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LAND ROVER', model:'FREELANDER', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MINI', model:'MINI', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MINI', model:'MINI CLUBMAN', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MINI', model:'MINI COUNTRYMAN', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MINI', model:'MINI PACEMAN', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PEUGEOT', model:'TRAVELLER', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PORSCHE', model:'CAYMAN', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PORSCHE', model:'MACAN', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PORSCHE', model:'PANAMERA', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'C30', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'S40', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'S60', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'S80', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'V50', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'V60', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'XC60', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'XC70', front:[{part:'3 397 006 947', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'A3', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'A4', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'E-TRON', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'Q2', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'Q3', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'Q5', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'X1 SERIES', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'X2 SERIES', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'CUPRA', model:'LEON', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'A-CLASS', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'B-CLASS', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'CLA-CLASS', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'EQA-CLASS', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'GLA-CLASS', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'GLE-CLASS', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PORSCHE', model:'CAYENNE', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PORSCHE', model:'PANAMERA', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SEAT', model:'LEON', rear:[{part:'3 397 008 635', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'ALFA ROMEO', model:'156', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BENTLEY', model:'FLYING SPUR', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'X5 SERIES', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'X6 SERIES', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'Z4 SERIES', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'CHRYSLER', model:'GRAND VOYAGER', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'CITROEN', model:'DISPATCH', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'DAIHATSU', model:'MATERIA', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'DAIHATSU', model:'SIRION', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HONDA', model:'CITY', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HONDA', model:'CIVIC', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HONDA', model:'CR-Z', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HONDA', model:'S2000', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HONDA', model:'S660', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HYUNDAI', model:'SONATA', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HYUNDAI', model:'STAREX', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HYUNDAI', model:'VERNA', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'KIA', model:'CERATO', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'KIA', model:'SORENTO', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LAND ROVER', model:'DISCOVERY SPORT', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LAND ROVER', model:'RANGE ROVER', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LAND ROVER', model:'RANGE ROVER SPORT', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LEXUS', model:'GS', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LEXUS', model:'IS', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LEXUS', model:'IS F', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LEXUS', model:'LS', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LEXUS', model:'SC', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MAZDA', model:'RX-8', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MITSUBISHI', model:'ECLIPSE', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MITSUBISHI', model:'MONTERO', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MITSUBISHI', model:'OUTLANDER', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'NISSAN', model:'350Z', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'NISSAN', model:'CABSTAR', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'NISSAN', model:'CEFIRO', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PERODUA', model:'KENARI', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PERODUA', model:'MYVI', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PROTON', model:'SATRIA', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PROTON', model:'WIRA', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SKODA', model:'SUPERB', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SSANGYONG', model:'REXTON', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SUBARU', model:'BRZ', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SUZUKI', model:'SWIFT', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'AVANZA', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'B B', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'CAMRY', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'DYNA', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'GT 86', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'HIACE', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'LAND CRUISER', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'MARK', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'MR2', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'TOYOACE', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'S60', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'V70', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'XC90', front:[{part:'3 397 013 318', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'ALFA ROMEO', model:'147', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'ALFA ROMEO', model:'156', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'3 SERIES', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'CHEVROLET', model:'AVEO', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'CHEVROLET', model:'OPTRA', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'CHEVROLET', model:'SPARK', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'CITROEN', model:'BERLINGO', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HONDA', model:'ACCORD', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HONDA', model:'CIVIC', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HONDA', model:'CROSSROAD', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HONDA', model:'JADE', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HONDA', model:'MOBILIO', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HYUNDAI', model:'GETZ', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HYUNDAI', model:'H1', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HYUNDAI', model:'TRAJET', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'HYUNDAI', model:'VERNA', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'JAGUAR', model:'X-TYPE', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'JEEP', model:'GRAND CHEROKEE', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'KIA', model:'PICANTO', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'KIA', model:'RIO', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LAND ROVER', model:'DISCOVERY', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LAND ROVER', model:'RANGE ROVER SPORT', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LEXUS', model:'IS', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LEXUS', model:'IS F', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LEXUS', model:'LX', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LEXUS', model:'RX', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MAZDA', model:'CX-3', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MAZDA', model:'MAZDA2', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MITSUBISHI', model:'AIRTREK', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MITSUBISHI', model:'ATTRAGE', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MITSUBISHI', model:'GALANT', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MITSUBISHI', model:'MIRAGE', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MITSUBISHI', model:'MONTERO', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MITSUBISHI', model:'OUTLANDER', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'NISSAN', model:'BLUEBIRD', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'NISSAN', model:'JUKE', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'NISSAN', model:'NV200', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'NISSAN', model:'NV350', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'NISSAN', model:'PULSAR', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'NISSAN', model:'SENTRA', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'NISSAN', model:'SUNNY', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PEUGEOT', model:'PARTNER', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'RENAULT', model:'KANGOO', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SAAB', model:'9-3', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SAAB', model:'9-5', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SUBARU', model:'BRZ', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SUBARU', model:'FORESTER', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SUBARU', model:'IMPREZA', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SUBARU', model:'R1', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SUBARU', model:'R2', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SUZUKI', model:'LIANA', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SUZUKI', model:'SOLIO', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'COMMUTER', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'FORTUNER', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'GT 86', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'HARRIER', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'HIACE', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'HILUX', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'IST', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'LAND CRUISER', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'MARK', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'TOYOTA', model:'SIENTA', front:[{part:'3 397 013 320', type:'Aerotwin Retro', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'C-CLASS', front:[{part:'3 397 118 938', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'CLS-CLASS', front:[{part:'3 397 118 938', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'E-CLASS', front:[{part:'3 397 118 938', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'E-SERIES', front:[{part:'3 397 118 938', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'OPEL', model:'ASTRA', front:[{part:'3 397 118 938', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'A4', front:[{part:'3 397 007 297', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'A5', front:[{part:'3 397 007 297', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'Q3', front:[{part:'3 397 007 297', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'Q5', front:[{part:'3 397 007 297', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PORSCHE', model:'MACAN', front:[{part:'3 397 007 297', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'S90', front:[{part:'3 397 007 297', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'XC40', front:[{part:'3 397 007 297', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'XC90', front:[{part:'3 397 007 297', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'CITROEN', model:'DS3', front:[{part:'3 397 007 118', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'DS', model:'DS3', front:[{part:'3 397 007 118', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'RENAULT', model:'FLUENCE', front:[{part:'3 397 007 118', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'RENAULT', model:'MEGANE', front:[{part:'3 397 007 118', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'CITROEN', model:'C5', front:[{part:'3 397 007 558', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'DS', model:'DS7', front:[{part:'3 397 007 558', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PEUGEOT', model:'3008', front:[{part:'3 397 007 558', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PEUGEOT', model:'5008', front:[{part:'3 397 007 558', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SEAT', model:'ALHAMBRA', front:[{part:'3 397 007 558', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLKSWAGEN', model:'CADDY', front:[{part:'3 397 007 558', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLKSWAGEN', model:'GOLF', front:[{part:'3 397 007 558', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLKSWAGEN', model:'SHARAN', front:[{part:'3 397 007 558', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLKSWAGEN', model:'TOURAN', front:[{part:'3 397 007 558', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'I3 SERIES', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'I8 SERIES', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'CITROEN', model:'C4', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'CITROEN', model:'DS4', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'CITROEN', model:'DS5', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'DS', model:'DS4', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'DS', model:'DS5', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'FORD', model:'GALAXY', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'FORD', model:'GRAND C-MAX', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'FORD', model:'S-MAX', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PEUGEOT', model:'308', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'PEUGEOT', model:'408', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'RENAULT', model:'GRAND SCENIC', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'RENAULT', model:'SCENIC', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLKSWAGEN', model:'ID.3', front:[{part:'3 397 006 954', type:'Aerotwin', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'A4', rear:[{part:'3 397 008 057', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'A6', rear:[{part:'3 397 008 057', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'Q3', rear:[{part:'3 397 008 057', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'Q8', rear:[{part:'3 397 008 057', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BENTLEY', model:'BENTAYGA', rear:[{part:'3 397 008 057', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'V-CLASS', rear:[{part:'3 397 008 057', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'ALPINA', model:'B5', rear:[{part:'3 397 008 192', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'1 SERIES', rear:[{part:'3 397 008 192', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'5 SERIES', rear:[{part:'3 397 008 192', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'X5 SERIES', rear:[{part:'3 397 008 192', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'V70', rear:[{part:'3 397 008 192', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'V90', rear:[{part:'3 397 008 192', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'XC40', rear:[{part:'3 397 008 192', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLVO', model:'XC90', rear:[{part:'3 397 008 192', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'SEAT', model:'TARRACO', rear:[{part:'3 397 016 087', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLKSWAGEN', model:'TIGUAN', rear:[{part:'3 397 016 087', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'VOLKSWAGEN', model:'TOUAREG', rear:[{part:'3 397 016 087', type:'Aerotwin Rear', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MAZDA', model:'CX-5', front:[{part:'3 397 014 398', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MAZDA', model:'CX-8', front:[{part:'3 397 014 398', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MAZDA', model:'CX-9', front:[{part:'3 397 014 398', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MAZDA', model:'MAZDA6', front:[{part:'3 397 014 398', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'E-CLASS', front:[{part:'3 397 014 242', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'GLB-CLASS', front:[{part:'3 397 014 242', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'ALPINA', model:'B3', front:[{part:'3 397 118 930', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'AUDI', model:'A3', front:[{part:'3 397 118 930', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'3 SERIES', front:[{part:'3 397 118 930', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'BMW', model:'X1 SERIES', front:[{part:'3 397 118 930', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'INFINITI', model:'Q30', front:[{part:'3 397 118 930', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'INFINITI', model:'QX30', front:[{part:'3 397 118 930', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'LAND ROVER', model:'FREELANDER', front:[{part:'3 397 118 930', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'A-CLASS', front:[{part:'3 397 118 930', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'CLA-CLASS', front:[{part:'3 397 118 930', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'},
  {make:'MERCEDES-BENZ', model:'GLA-CLASS', front:[{part:'3 397 118 930', type:'Aerotwin set', source:'Bosch AutoParts Catalogue'}], confidence:'catalogue-model'}
];
const DB = [...LEGACY, ...OFFICIAL];

function norm(s){return String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
function match(v){
 const make=norm(v.merk), model=norm(v.handelsbenaming||v.model), year=Number(v.bouwjaar||v.modeljaar||0)||0;
 const hits=DB.filter(x=>{
   if(norm(x.make)!==make) return false;
   const xm=norm(x.model);
   if(!model.includes(xm) && !xm.includes(model)) return false;
   if(x.from && year && year<x.from) return false;
   if(x.to && year && year>x.to) return false;
   return true;
 });
 const out={front:[],rear:[],confidence:'catalogue-model',sources:['Bosch AutoParts Catalogue / Bosch application catalogues']};
 for(const h of hits){
   for(const a of (h.front||[])) out.front.push({...a,position:'Voor'});
   for(const a of (h.rear||[])) out.rear.push({...a,position:'Achter'});
   if(h.confidence==='exact-model-generation') out.confidence='exact-model-generation';
 }
 const uniq=a=>a.filter((x,i)=>i===a.findIndex(y=>y.part===x.part && y.position===x.position));
 out.front=uniq(out.front); out.rear=uniq(out.rear);
 return {vehicle:{make,model,year},...out,found:out.front.length+out.rear.length>0,source:'Bosch AutoParts Catalogue / Bosch application catalogues',sourceUrl:'https://www.boschwiperblades.com/'};
}
export default async function handler(req,res){
 if(req.method!=='GET') return res.status(405).json({error:'GET vereist.'});
 try{const q=req.query||{}; return res.json(match({merk:q.merk,model:q.model,handelsbenaming:q.handelsbenaming,bouwjaar:q.bouwjaar,modeljaar:q.modeljaar}));}
 catch(e){return res.status(500).json({error:'Wisserdatabase kon niet worden gelezen.'});}
}
